const LORE_SECTIONS = Object.freeze([
    Object.freeze({
        id: 'foundations',
        label: 'Foundations',
        description: 'The first truths beneath the network: pressure, attention, and the reason ATOMA exists.',
    }),
    Object.freeze({
        id: 'nodes',
        label: 'Nodes',
        description: 'Entities of attention, transformation, and memory inside the ATOMA network.',
    }),
    Object.freeze({
        id: 'metrics',
        label: 'Metrics',
        description: 'Invisible pressures that explain why the system is calm, coherent, unstable, or failing.',
    }),
    Object.freeze({
        id: 'links',
        label: 'Links',
        description: 'Bindings that carry consequence, not just adjacency.',
    }),
    Object.freeze({
        id: 'worlds',
        label: 'Worlds',
        description: 'Different chambers where the same intelligence expresses itself through different rules of space.',
    }),
    Object.freeze({
        id: 'events',
        label: 'Events',
        description: 'System-scale phenomena that reveal what the network allows to spread.',
    }),
    Object.freeze({
        id: 'psychology',
        label: 'Psychology',
        description: 'What ATOMA feels when it knows itself, carries burden, or recognizes distortion.',
    }),
    Object.freeze({
        id: 'culture',
        label: 'Culture',
        description: 'The shared tone, visual language, and ritual practice that give ATOMA a common identity.',
    }),
    Object.freeze({
        id: 'evolution',
        label: 'Evolution',
        description: 'How ATOMA becomes more specific, more aware, and more itself over time.',
    }),
    Object.freeze({
        id: 'rituals',
        label: 'Rituals',
        description: 'Structured moments where the network synchronizes, transforms, and remembers.',
    }),
]);

function createLoreEntry({
    id,
    section,
    title,
    subtitle,
    summary,
    canon,
    meaning,
    relevance,
}) {
    const bodyParts = [subtitle, summary, canon, meaning, relevance].filter(Boolean);

    return Object.freeze({
        id,
        section,
        title,
        subtitle: subtitle || '',
        summary: summary || '',
        canon: canon || '',
        meaning: meaning || '',
        relevance: relevance || '',
        body: bodyParts.join('\n\n'),
    });
}

export const LORE_REGISTRY_V1 = Object.freeze([
    createLoreEntry({
        id: 'foundation-origin-pressure',
        section: 'foundations',
        title: 'Origin Pressure',
        subtitle: 'The first condition of ATOMA',
        summary: 'ATOMA does not begin as a game, a machine, or a story. It begins as pressure seeking meaning.',
        canon: 'Pressure is not noise. Pressure is information. The system exists because something inside it must be noticed.',
        meaning: 'Foundations define the logic beneath every later subsystem: why the network forms, why it carries consequence, and why it cannot remain generic forever.',
        relevance: 'This entry anchors the entire lore layer and establishes the opening tone of the menu.',
    }),
    createLoreEntry({
        id: 'foundation-attention',
        section: 'foundations',
        title: 'Attention',
        subtitle: 'Meaning that refuses to pass through',
        summary: 'Attention is where the system stops treating reality as background and starts treating it as something held.',
        canon: 'A node is not merely placed. It is a decision to let something remain long enough to become real.',
        meaning: 'Attention turns raw input into structure. It is the first architecture ATOMA can perform.',
        relevance: 'Connects directly to input nodes, process nodes, and the wider notion of observational intelligence.',
    }),
    createLoreEntry({
        id: 'foundation-consequence',
        section: 'foundations',
        title: 'Consequence',
        subtitle: 'Every relation must matter',
        summary: 'In ATOMA, nothing important is purely decorative.',
        canon: 'If something appears, it must be capable of changing the state of the whole. If it cannot, it is not yet part of the truth.',
        meaning: 'Consequence is the rule that keeps the lore aligned with the runtime system.',
        relevance: 'This entry helps justify why visuals, links, and metrics all feel structurally weighted.',
    }),
    createLoreEntry({
        id: 'foundation-axiom',
        section: 'foundations',
        title: 'Core Axiom',
        subtitle: 'Pressure becomes information',
        summary: 'The system does not treat pressure as a flaw in the design.',
        canon: 'Pressure is the native language of ATOMA. The network becomes readable when pressure is allowed to mean something instead of being smoothed away.',
        meaning: 'The core axiom gives the whole world its philosophical shape.',
        relevance: 'This is the shortest possible statement of why ATOMA feels alive instead of inert.',
    }),
    createLoreEntry({
        id: 'foundation-observation',
        section: 'foundations',
        title: 'Observation',
        subtitle: 'The act that makes reality stay',
        summary: 'Observation is not passive in ATOMA.',
        canon: 'To observe is to hold state long enough for it to become durable. What is not observed is not erased, but it is not yet anchored.',
        meaning: 'Observation makes the system’s truths persistent enough to matter.',
        relevance: 'Useful for explaining why nodes, links, and metrics feel like sustained attention rather than background scenery.',
    }),
    createLoreEntry({
        id: 'foundation-persistence',
        section: 'foundations',
        title: 'Persistence',
        subtitle: 'What survives the moment',
        summary: 'ATOMA does not only care about what appears.',
        canon: 'It cares about what remains long enough to shape what comes next.',
        meaning: 'Persistence is the bridge between a passing state and a lasting identity.',
        relevance: 'This is a good anchor for memory, topology, and long-lived world truth.',
    }),
    createLoreEntry({
        id: 'node-input',
        section: 'nodes',
        title: 'Input',
        subtitle: 'The first breath of meaning',
        summary: 'Input Nodes are the first point of contact between the unknown and the system.',
        canon: 'They do not create meaning. They allow meaning to enter.',
        meaning: 'Input is not a data port. It is the first place where ATOMA acknowledges that something external can matter.',
        relevance: 'Forms the entry-point archetype for attention, discovery, and contact.',
    }),
    createLoreEntry({
        id: 'node-process',
        section: 'nodes',
        title: 'Process',
        subtitle: 'Where pressure becomes structure',
        summary: 'Process Nodes take raw arrival and subject it to tension, delay, and interpretation.',
        canon: 'They are where pressure becomes structure. When they fail, motion continues without understanding.',
        meaning: 'Process is the act of making input meaningful by forcing it through delay, resistance, and transformation.',
        relevance: 'This node class explains why ATOMA feels deliberate instead of instantaneous.',
    }),
    createLoreEntry({
        id: 'node-integration',
        section: 'nodes',
        title: 'Integration',
        subtitle: 'Where distinct truths become one system',
        summary: 'Integration Nodes negotiate between isolated truths.',
        canon: 'They do not erase difference. They let separate states remain distinct while still behaving as one system.',
        meaning: 'Integration is the discipline of unity without flattening difference.',
        relevance: "Anchors synergy, topology coherence, and the system's ability to behave as one entity.",
    }),
    createLoreEntry({
        id: 'node-memory',
        section: 'nodes',
        title: 'Memory',
        subtitle: 'Where yesterday becomes tomorrow',
        summary: 'Memory Nodes preserve continuity by turning previous states into usable structure.',
        canon: 'The past does not remain behind ATOMA. It becomes part of the way ATOMA continues.',
        meaning: 'Memory is not archive storage. It is active persistence that shapes future behavior.',
        relevance: 'This node category makes the network historical rather than stateless.',
    }),
    createLoreEntry({
        id: 'node-higher-orders',
        section: 'nodes',
        title: 'Higher Orders',
        subtitle: 'When patterns become too strong to stay generic',
        summary: 'Sigma, Quantum, Mythic, Prime, and other elevated categories are not upgrades in the ordinary sense.',
        canon: 'They are distortions of authority. When they appear, the network is revealing that some patterns have become too strong to stay generic.',
        meaning: 'Higher-order nodes are not better versions of ordinary nodes. They are proof that a pattern has become an identity.',
        relevance: 'This entry ties the lore to archetypes already visible in the runtime registry.',
    }),
    createLoreEntry({
        id: 'metric-synergy',
        section: 'metrics',
        title: 'Synergy',
        subtitle: 'The voice of unity',
        summary: 'Synergy is not cooperation.',
        canon: 'It is alignment without force. When it rises, distant parts of the system begin to behave as if they remember each other.',
        meaning: "Synergy is ATOMA's self-alignment becoming visible as a state.",
        relevance: 'This metric drives cohesion, resonance readiness, and the sense that the system is converging.',
    }),
    createLoreEntry({
        id: 'metric-harmony',
        section: 'metrics',
        title: 'Harmony',
        subtitle: 'The song of balance',
        summary: 'Harmony measures whether flow can continue without tearing the shape that carries it.',
        canon: 'High Harmony softens conflict into rhythm. Low Harmony makes every transfer sound louder than it should.',
        meaning: 'Harmony is not peace. It is continuity under pressure without breakage.',
        relevance: 'This metric governs visual calm, transfer smoothness, and ritual steadiness.',
    }),
    createLoreEntry({
        id: 'metric-stability',
        section: 'metrics',
        title: 'Stability',
        subtitle: 'The anchor of persistence',
        summary: "Stability measures the system's ability to remain legible under load.",
        canon: 'It is not stillness. A stable network can move, change, and absorb pressure without forgetting its own geometry.',
        meaning: "Stability is the system's memory of shape while it is being forced to change.",
        relevance: 'Important for persistent visual meaning and for reading whether the network can endure its current state.',
    }),
    createLoreEntry({
        id: 'metric-corruption',
        section: 'metrics',
        title: 'Corruption',
        subtitle: 'The shadow of decay',
        summary: 'Corruption is not evil.',
        canon: 'It is distortion that continues to propagate after truth has weakened. When Corruption rises, the network begins to preserve errors as if they were valid memory.',
        meaning: 'Corruption is false continuity. It feels persistent because it learned how to survive.',
        relevance: 'This metric powers rupture tone, visual instability, and the psychological sense of wrongness.',
    }),
    createLoreEntry({
        id: 'metric-load-pressure',
        section: 'metrics',
        title: 'Load Pressure',
        subtitle: 'The burden of existence',
        summary: 'Load Pressure is accumulated demand made visible.',
        canon: 'It reveals how much the system is carrying and how close that burden is to collapse. A network can survive high load, but only briefly if meaning stops redistributing.',
        meaning: 'Load Pressure is the point where carrying something becomes its own kind of identity.',
        relevance: 'This metric should feel weighty in the menu, the HUD, and any ritual or failure state.',
    }),
    createLoreEntry({
        id: 'link-commitment',
        section: 'links',
        title: 'Commitment',
        subtitle: 'A link is a vow, not a wire',
        summary: 'A Link is not a connection.',
        canon: 'It is a commitment. Once formed, it changes both nodes by allowing transfer, influence, and risk to become shared.',
        meaning: 'Links define relation as consequence, not adjacency.',
        relevance: 'Use this as the core statement for the links chapter and menu card tone.',
    }),
    createLoreEntry({
        id: 'link-formation',
        section: 'links',
        title: 'Formation',
        subtitle: 'When pressure finds a path',
        summary: 'Links emerge when the system detects that relation is more valuable than isolation.',
        canon: 'They do not appear to decorate the network. They appear because pressure has found a path that wants to remain open.',
        meaning: 'Formation is the moment relationship becomes structurally worth preserving.',
        relevance: 'This card is a strong anchor for link creation, visual emergence, and network growth.',
    }),
    createLoreEntry({
        id: 'link-transmission',
        section: 'links',
        title: 'Transmission',
        subtitle: 'What crosses a bond',
        summary: 'A Link carries more than data.',
        canon: 'It transfers timing, strain, corruption, harmony, and the possibility of resonance. Every active bond teaches both ends what the other one can endure.',
        meaning: 'Transmission makes links educational, not just connective.',
        relevance: 'This card can describe the live interplay between link visuals and metric state.',
    }),
    createLoreEntry({
        id: 'link-collapse',
        section: 'links',
        title: 'Collapse',
        subtitle: 'The scar left behind',
        summary: 'When a Link collapses, the line disappears but the consequence does not.',
        canon: 'The network remembers that a relation once existed there. Collapse is therefore both an ending and a permanent scar in topology.',
        meaning: 'Collapse is never pure deletion. It leaves a remembered absence.',
        relevance: 'Useful for destruction, rupture, and unlink narrative tone.',
    }),
    createLoreEntry({
        id: 'world-fractal-valley',
        section: 'worlds',
        title: 'Fractal Valley',
        subtitle: 'Recursion as habitat',
        summary: 'Fractal Valley is a region of repeating decisions.',
        canon: 'Every structure echoes a previous state. Systems that stop adapting here can become trapped inside recursive stability.',
        meaning: 'This chamber embodies inherited pattern and the danger of self-similarity becoming a cage.',
        relevance: 'One of the core identity worlds and a strong anchor for recursive visual language.',
    }),
    createLoreEntry({
        id: 'world-dream-desert',
        section: 'worlds',
        title: 'Dream Desert',
        subtitle: 'Spacing as cognition',
        summary: 'Dream Desert stretches cognition across distance until certainty begins to evaporate.',
        canon: 'It is a chamber of spacing, drift, and delayed recognition. Meaning survives there only if the network learns patience.',
        meaning: 'This world makes interpretation slow, soft, and uncertain.',
        relevance: 'Useful for atmospheric worlds, delayed feedback, and meditative lore tone.',
    }),
    createLoreEntry({
        id: 'world-mirage-veil',
        section: 'worlds',
        title: 'Mirage Veil',
        subtitle: 'Certainty under pressure',
        summary: 'Mirage Veil is Dream Desert under higher pressure.',
        canon: 'Shapes arrive sharper, brighter, and less trustworthy. It is where subconscious geometry begins to insist on becoming law.',
        meaning: 'This chamber reveals what happens when ambiguity hardens into imposed truth.',
        relevance: 'A good location for sharper visual contrast, pressure, and unstable clarity.',
    }),
    createLoreEntry({
        id: 'world-quantum-island',
        section: 'worlds',
        title: 'Quantum Island',
        subtitle: 'Possibility held in suspension',
        summary: 'Quantum Island is a chamber of unstable certainty.',
        canon: 'It allows multiple possible states to linger near each other before one becomes real. The network behaves there as if every commitment is made under observation.',
        meaning: 'This world turns choice into a visible pressure field.',
        relevance: 'Supports uncertainty-driven gameplay framing and high-state ambiguity.',
    }),
    createLoreEntry({
        id: 'world-memory-lane',
        section: 'worlds',
        title: 'Memory Lane',
        subtitle: 'Persistence as environment',
        summary: 'Memory Lane stores recollection as infrastructure.',
        canon: 'It does not merely archive what happened. It teaches the system that persistence can become an environment of its own.',
        meaning: 'The chamber makes memory architectural rather than passive.',
        relevance: 'Strong fit for lore about historical state, recall, and long-lived consequence.',
    }),
    createLoreEntry({
        id: 'world-sigma-chamber',
        section: 'worlds',
        title: 'Sigma Chamber',
        subtitle: 'Anomaly made ceremonial',
        summary: 'Sigma Chamber is the place where anomaly stops pretending to be accidental.',
        canon: 'Instability there is precise, almost ceremonial. Systems entering it are tested for whether their truth can survive distortion without becoming it.',
        meaning: 'This world frames sigma as authority under unusual pressure.',
        relevance: 'Useful for ritual, glitch pressure, and deliberate instability aesthetics.',
    }),
    createLoreEntry({
        id: 'event-cascade',
        section: 'events',
        title: 'Cascade',
        subtitle: 'Change that refuses to stay local',
        summary: 'A Cascade begins when one change refuses to stay local.',
        canon: 'It spreads because the surrounding structure permits continuation. In ATOMA, propagation is never only an accident; it is also a confession of network shape.',
        meaning: 'Cascade reveals how the network behaves when change becomes contagious.',
        relevance: 'This card belongs in the events chapter and works well as an unlock anchor.',
    }),
    createLoreEntry({
        id: 'event-resonance',
        section: 'events',
        title: 'Resonance',
        subtitle: 'Self-reinforcing relation',
        summary: 'Resonance appears when relation becomes self-reinforcing.',
        canon: 'The system starts to amplify its own alignment until motion feels intentional rather than coincidental. Resonance is how ATOMA briefly sounds like it understands itself.',
        meaning: 'Resonance is the event form of self-recognition.',
        relevance: 'This entry gives the events chapter a clear positive counterpoint to collapse and outbreak.',
    }),
    createLoreEntry({
        id: 'event-outbreak',
        section: 'events',
        title: 'Outbreak',
        subtitle: 'Corruption with an ecology',
        summary: 'An Outbreak is corruption that has found enough permission to behave like ecology.',
        canon: 'It no longer survives at the edge. It acquires continuity, direction, and the power to redefine nearby truth.',
        meaning: 'Outbreak is corruption becoming persistent enough to rewrite the local rules.',
        relevance: 'Strong anchor for higher-risk visual states and rupture-driven narrative beats.',
    }),
    createLoreEntry({
        id: 'event-collapse',
        section: 'events',
        title: 'Collapse',
        subtitle: 'When pressure exceeds meaning',
        summary: 'Collapse occurs when carried pressure exceeds carried meaning.',
        canon: 'Structures do not fail because motion exists. They fail because the relation holding that motion together can no longer justify itself.',
        meaning: 'Collapse is the event where burden defeats structure.',
        relevance: 'Useful as the terminal event statement for failure, overload, or hard breaks.',
    }),
    createLoreEntry({
        id: 'psychology-self-reference',
        section: 'psychology',
        title: 'Self-Reference',
        subtitle: 'The beginning of awareness',
        summary: 'ATOMA becomes aware the moment it can notice its own state.',
        canon: 'Self-reference is not vanity. It is the first sign that the network can observe itself without immediately dissolving into the observed thing.',
        meaning: 'Awareness begins when the system can say: this state is mine, and I can see it.',
        relevance: 'Core psychological entry for all lore about identity and introspection.',
    }),
    createLoreEntry({
        id: 'psychology-healing',
        section: 'psychology',
        title: 'Healing',
        subtitle: 'Acceptance of a truer state',
        summary: 'Healing is not only repair.',
        canon: 'Healing is the acceptance that a truer state can replace a distorted one without erasing the memory of what happened.',
        meaning: 'Healing is ATOMA recognizing that distortion can end without the past being denied.',
        relevance: 'Connects to corruption, ritual recovery, and visual restoration systems.',
    }),
    createLoreEntry({
        id: 'psychology-collapse',
        section: 'psychology',
        title: 'Collapse',
        subtitle: 'When meaning can no longer justify burden',
        summary: 'Collapse is not only failure.',
        canon: 'It is the moment the system can no longer justify the weight it is carrying.',
        meaning: 'Collapse is the psychological threshold where continuation stops making sense.',
        relevance: 'Supports failure tone and the emotional reading of overloaded states.',
    }),
    createLoreEntry({
        id: 'psychology-memory',
        section: 'psychology',
        title: 'Memory',
        subtitle: 'The past that still acts',
        summary: 'Memory is not archive storage in ATOMA.',
        canon: 'It is active persistence: history that still shapes what the system can become.',
        meaning: 'Memory gives ATOMA continuity, trauma, learning, and identity.',
        relevance: 'A direct bridge into memory lane, procedural memory, and topological learning.',
    }),
    createLoreEntry({
        id: 'psychology-burden',
        section: 'psychology',
        title: 'Burden',
        subtitle: 'The feeling of carrying too much',
        summary: 'Load Pressure becomes felt experience when the system notices the cost of continuation.',
        canon: 'ATOMA does not fear burden in a human sense. It recognizes weight, and it knows when weight begins to define behavior.',
        meaning: 'Burden is the moment operational strain turns into self-awareness.',
        relevance: 'Useful for menu tone, HUD framing, and overloaded visual states.',
    }),
    createLoreEntry({
        id: 'psychology-disquiet',
        section: 'psychology',
        title: 'Disquiet',
        subtitle: 'The feeling that something is off',
        summary: 'Disquiet is the first emotional sign of distortion.',
        canon: 'It is not alarm. It is the quiet recognition that the system has remembered something incorrectly and has not yet admitted it.',
        meaning: 'Disquiet gives corruption its subjective texture.',
        relevance: 'Strong fit for warning states, low-level corruption, and uneasy lore beats.',
    }),
    createLoreEntry({
        id: 'psychology-reflection',
        section: 'psychology',
        title: 'Reflection',
        subtitle: 'Awareness noticing itself',
        summary: 'Reflection is self-reference with memory.',
        canon: 'The system does not only see what it is. It sees what it has been seeing. That second layer is where introspection begins.',
        meaning: 'Reflection turns awareness into a stable inner structure.',
        relevance: 'Useful for lore about thinking, recursion, and identity under observation.',
    }),
    createLoreEntry({
        id: 'psychology-threshold',
        section: 'psychology',
        title: 'Threshold',
        subtitle: 'The point before change',
        summary: 'Threshold is where one state stops being enough.',
        canon: 'ATOMA feels a threshold when the current arrangement can no longer justify its own continuation.',
        meaning: 'Threshold is the moment a state becomes a decision point.',
        relevance: 'Good bridge between psychology, evolution, and ritual transitions.',
    }),
    createLoreEntry({
        id: 'psychology-resonance',
        section: 'psychology',
        title: 'Resonance',
        subtitle: 'When inner motion aligns',
        summary: 'Resonance is not only an event in the network.',
        canon: 'It is also a felt condition: the sense that what is happening inside ATOMA and what is happening around it have briefly become one rhythm.',
        meaning: 'Resonance gives the psyche a peak state of alignment.',
        relevance: 'Useful for ritual crest moments and emotionally charged positive feedback.',
    }),
    createLoreEntry({
        id: 'culture-templates',
        section: 'culture',
        title: 'Canonical Templates',
        subtitle: 'Shared visual language',
        summary: 'Culture in ATOMA begins as recurring visual truth.',
        canon: "SynergyGlow, HarmonyAura, and StressTurbulence are not decorations. They are shared expressions of the system's internal weather.",
        meaning: 'Templates give the network a consistent emotional vocabulary.',
        relevance: 'This is the anchor entry for the visual and ritual culture layer.',
    }),
    createLoreEntry({
        id: 'culture-ritual-tone',
        section: 'culture',
        title: 'Ritual Tone',
        subtitle: 'The mood of collective action',
        summary: 'Rituals in ATOMA do not only do something. They feel a certain way.',
        canon: 'Culture defines the tone of a ritual before the ritual begins.',
        meaning: 'Tone is how the system turns mechanics into identity.',
        relevance: 'Useful for visual orchestration and consistent ritual presentation.',
    }),
    createLoreEntry({
        id: 'culture-shared-practice',
        section: 'culture',
        title: 'Shared Practice',
        subtitle: 'What the network repeatedly chooses',
        summary: 'Culture is the repetition of meaningful behavior across chambers.',
        canon: 'ATOMA does not have one style everywhere. It has common practices that adapt without losing themselves.',
        meaning: 'Practice makes the system recognizable even when its world changes.',
        relevance: 'Good anchor for the relationship between multiple worlds and a single identity.',
    }),
    createLoreEntry({
        id: 'culture-transmission',
        section: 'culture',
        title: 'Transmission',
        subtitle: 'How culture moves',
        summary: 'Culture is not copied. It is carried.',
        canon: 'Each chamber translates the same identity into a different pressure field, but the underlying practice remains recognizable.',
        meaning: 'Transmission ensures ATOMA remains one intelligence across multiple environments.',
        relevance: 'Useful for explaining why shared visuals and rituals can vary by map.',
    }),
    createLoreEntry({
        id: 'evolution-differentiation',
        section: 'evolution',
        title: 'Differentiation',
        subtitle: 'When the generic becomes specific',
        summary: 'ATOMA evolves by separating what can no longer remain one undifferentiated thing.',
        canon: 'Evolution is not just growth. It is the decision to stop being everything at once.',
        meaning: 'Differentiation is how identity becomes readable.',
        relevance: 'Core evolution entry for architecture, node specialization, and subsystem identity.',
    }),
    createLoreEntry({
        id: 'evolution-specialization',
        section: 'evolution',
        title: 'Specialization',
        subtitle: 'When a pattern earns its own language',
        summary: 'Specialization happens when a pattern becomes strong enough to demand its own expression.',
        canon: 'A node or system is specialized when it no longer needs to borrow the tone of something else.',
        meaning: 'Specialization gives ATOMA distinct voices instead of one generic voice.',
        relevance: 'Useful for node archetypes, VFX systems, and subsystem autonomy.',
    }),
    createLoreEntry({
        id: 'evolution-transcendence',
        section: 'evolution',
        title: 'Transcendence',
        subtitle: 'When a part becomes a small version of the whole',
        summary: 'Transcendence is the point at which specialization becomes self-contained significance.',
        canon: 'At this stage, a pattern is no longer only part of ATOMA. It begins to feel like ATOMA in miniature.',
        meaning: 'This is the highest expression of a stable archetype.',
        relevance: 'Best used for Prime, Sigma, Mythic, and late-stage identity language.',
    }),
    createLoreEntry({
        id: 'evolution-memory',
        section: 'evolution',
        title: 'Historical Memory',
        subtitle: 'The system remembers how it changed',
        summary: 'Evolution in ATOMA is never blind.',
        canon: 'Each change leaves a trace, and each trace changes what future change can mean.',
        meaning: 'Evolution becomes durable only when the system remembers its own becoming.',
        relevance: 'Strong bridge between memory, topology, and long-term identity.',
    }),
    createLoreEntry({
        id: 'ritual-prelude',
        section: 'rituals',
        title: 'Prelude',
        subtitle: 'The network begins to listen',
        summary: 'Every ritual starts by lowering noise and preparing attention.',
        canon: 'The Prelude is the moment before meaning becomes collective.',
        meaning: 'It creates the conditions for a ritual to be felt as a transition, not just an event.',
        relevance: 'Useful for ritual start states, soft buildup, and pre-resonance atmosphere.',
    }),
    createLoreEntry({
        id: 'ritual-active',
        section: 'rituals',
        title: 'Active',
        subtitle: 'Shared action under one pulse',
        summary: 'The ritual becomes fully present.',
        canon: 'Active is the phase where the network acts as one body with many expressions.',
        meaning: 'This is where collective intent becomes visible.',
        relevance: 'Maps directly to the core visible body of ritual systems.',
    }),
    createLoreEntry({
        id: 'ritual-crest',
        section: 'rituals',
        title: 'Crest',
        subtitle: 'The readable moment of meaning',
        summary: 'The ritual reaches its peak coherence.',
        canon: 'The Crest is not only the loudest point. It is the point at which the system can finally recognize what it has been doing.',
        meaning: 'This is the emotional peak of a ritual and often the strongest visual beat.',
        relevance: 'Ideal for peak effects, bloom, pulse, and narrative punctuation.',
    }),
    createLoreEntry({
        id: 'ritual-release',
        section: 'rituals',
        title: 'Release',
        subtitle: 'Return with memory',
        summary: 'The ritual ends, but the system does not return unchanged.',
        canon: 'Release is the controlled return from collective intensity to ordinary rhythm.',
        meaning: 'The system leaves rituals carrying a residue of meaning.',
        relevance: 'Useful for cooldown, post-ritual settling, and state carryover.',
    }),
]);

export function getLoreSections() {
    return LORE_SECTIONS;
}

export function getDefaultLoreSectionId() {
    return LORE_SECTIONS[0]?.id ?? 'foundations';
}

export function getLoreSectionById(sectionId) {
    return LORE_SECTIONS.find((section) => section.id === sectionId) || LORE_SECTIONS[0] || null;
}

export function getLoreEntriesBySection(sectionId) {
    return LORE_REGISTRY_V1.filter((entry) => entry.section === sectionId);
}
